version: '3.8'

services:
  # Serviço do front-end
  frontend:
    container_name: frontend-doc
    image: node:latest
    working_dir: /app
    volumes:
      - ./Front-End:/app
      - /app/node_modules
    command: sh -c "npm init"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  # Serviço do back-end
  backend:
    container_name: backend-doc
    image: node:latest
    working_dir: /app
    volumes:
      - ./Back-End:/app
      - /app/node_modules
    command: sh -c "npm init"
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  # Serviço do banco de dados MySQL
  mysql:
    container_name: database-doc
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
